### ISSUE TITLE
请问大佬有没有国服商店的API

### ISSUE THREAD

**Issue by NNanfeng** [Dylan379/wxmini-ValDailyshopServer#1]
如题所述 想要API写一个东西

**Comment by Dylan379** [comment]
你好,我是参考的已经封装好的国际服商店API库,参考[val-shop (v2)](https://val.musnow.top/doc-2423048),具体是否支持国服你可以自行尝试,或者到[Kook群](https://www.kookapp.cn/app/invite/gpbTwZ),联系原作者询问

**Comment by NNanfeng** [comment]
好的，谢谢您的解答
